# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_event_verein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='zeit',
        ),
        migrations.AddField(
            model_name='event',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now, help_text='e.g. 27.2.2018'),
        ),
    ]
