# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_auto_20171226_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datum',
            field=models.DateField(blank=True, help_text='e.g. 27.2.2018', null=True),
        ),
    ]
