# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0006_auto_20171227_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='geom',
        ),
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
