# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0007_auto_20171227_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
